export const rooms = [
  { name: 'Hotel Nile View', location: 'Cairo, Egypt' },
  { name: 'The Royal Pyramid', location: 'Giza, Egypt' },
  { name: 'Desert Sands Resort', location: 'Luxor, Egypt' },
  { name: 'Red Sea Breeze', location: 'Hurghada, Egypt' },
  { name: 'Oasis Hotel', location: 'Alexandria, Egypt' },
  { name: "Pharaoh's Palace", location: 'Cairo, Egypt' },
  { name: 'Temple View Hotel', location: 'Aswan, Egypt' },
  { name: 'Sphinx Suites', location: 'Giza, Egypt' },
  { name: 'Blue Nile Inn', location: 'Cairo, Egypt' },
  { name: 'Mediterranean Breeze', location: 'Alexandria, Egypt' },
  { name: 'Luxor Grand Hotel', location: 'Luxor, Egypt' },
  { name: 'Sharm Paradise Resort', location: 'Sharm El-Sheikh, Egypt' },
  { name: 'Cairo Sunset Hotel', location: 'Cairo, Egypt' },
  { name: 'Ancient Sands Resort', location: 'Hurghada, Egypt' },
  { name: 'Pyramid Peak Inn', location: 'Giza, Egypt' },
  { name: 'The Nile Palace', location: 'Cairo, Egypt' },
  { name: 'Horizon Nile View', location: 'Aswan, Egypt' },
  { name: 'The Alexandria Inn', location: 'Alexandria, Egypt' },
  { name: 'Golden Sands Hotel', location: 'Hurghada, Egypt' },
  { name: 'Cairo Sky Suites', location: 'Cairo, Egypt' },
  { name: 'Sahara Oasis Resort', location: 'Luxor, Egypt' },
  { name: 'The Royal Pharaoh', location: 'Giza, Egypt' },
  { name: 'The Blue Pyramid', location: 'Cairo, Egypt' },
  { name: 'Tahrir Square Hotel', location: 'Cairo, Egypt' },
  { name: 'Golden Nile Suites', location: 'Aswan, Egypt' },
  { name: 'Mediterranean Sands Resort', location: 'Alexandria, Egypt' },
  { name: 'Sharm Blue Bay', location: 'Sharm El-Sheikh, Egypt' },
  { name: 'Luxor Horizon', location: 'Luxor, Egypt' },
  { name: 'Pyramid Valley Resort', location: 'Giza, Egypt' },
  { name: 'Red Sea Horizon', location: 'Hurghada, Egypt' },
  { name: 'The Grand Nile', location: 'Cairo, Egypt' },
  { name: 'Temple Sands Hotel', location: 'Aswan, Egypt' },
  { name: 'The Mediterranean Pearl', location: 'Alexandria, Egypt' },
  { name: 'Giza Heights Resort', location: 'Giza, Egypt' },
  { name: "The Pharaoh's Retreat", location: 'Cairo, Egypt' },
  { name: 'Aswan Sky Suites', location: 'Aswan, Egypt' },
  { name: 'Luxor Temple Resort', location: 'Luxor, Egypt' },
  { name: 'Blue Lagoon Resort', location: 'Hurghada, Egypt' },
  { name: 'The Sphinx View', location: 'Giza, Egypt' },
  { name: 'Sunset Sands Resort', location: 'Sharm El-Sheikh, Egypt' },
  { name: 'The Cairo Crown', location: 'Cairo, Egypt' },
  { name: 'Palm Oasis Hotel', location: 'Sharm El-Sheikh, Egypt' },
  { name: 'The Nile Jewel', location: 'Aswan, Egypt' },
  { name: 'The Pyramid Resort', location: 'Giza, Egypt' },
  { name: 'Cairo Golden Plaza', location: 'Cairo, Egypt' },
  { name: 'Alexandria Harbor Resort', location: 'Alexandria, Egypt' },
];
